window.QAG_DISTRICTS = [
  'Abura Asebu Kwamankese District',
  'Abuakwa North Municipal',
  'Abuakwa South Municipal',
  'Accra Metropolitan Assembly',
  'Ada East District',
  'Ada West District',
  'Adaklu District',
  'Adansi Asokwa District',
  'Adansi North District',
  'Adansi South District',
  'Adentan Municipal',
  'Afadzato South District',
  'Afigya Kwabre North District',
  'Afigya Kwabre South District',
  'Agona East District',
  'Agona West Municipal',
  'Agotime Ziope District',
  'Ahafo Ano North Municipal',
  'Ahafo Ano South East District',
  'Ahafo Ano South West District',
  'Ahanta West Municipal',
  'Ajumako Enyan Essiam District',
  'Akyemansa District',
  'Akatsi North District',
  'Akatsi South Municipal',
  'Akuapem North Municipal',
  'Akuapem South Municipal',
  'Amenfi Central District',
  'Amenfi East Municipal',
  'Amenfi West Municipal',
  'Amansie Central District',
  'Amansie South District',
  'Amansie West District',
  'Anloga District',
  'Aowin Municipal',
  'Asante Akim Central Municipal',
  'Asante Akim North District',
  'Asante Akim South Municipal',
  'Asene Manso Akroso District',
  'Ashaiman Municipal',
  'Asikuma Odoben Brakwa District',
  'Asokore Mampong Municipal',
  'Asokwa Municipal',
  'Asunafo North Municipal',
  'Asunafo South District',
  'Asutifi North District',
  'Asutifi South District',
  'Atiwa East District',
  'Atiwa West District',
  'Atwima Kwanwoma District',
  'Atwima Mponua District',
  'Atwima Nwabiagya Municipal',
  'Awutu Senya East Municipal',
  'Awutu Senya West District',
  'Ayawaso Central Municipal',
  'Ayawaso East Municipal',
  'Ayawaso North Municipal',
  'Ayawaso West Municipal',
  'Ayensuano District',
  'Banda District',
  'Bawku Municipal',
  'Bawku West District',
  'Bekwai Municipal',
  'Berekum East Municipal',
  'Berekum West District',
  'Bia East District',
  'Bia West District',
  'Biakoye District',
  'Bibiani Anhwiaso Bekwai Municipal',
  'Binduri District',
  'Birim Central Municipal',
  'Birim North District',
  'Birim South District',
  'Bole District',
  'Bolgatanga Municipal',
  'Bongo District',
  'Bosome Freho District',
  'Bosomtwe District',
  'Builsa North Municipal',
  'Builsa South District',
  'Bunkpurugu Nakpanduri District',
  'Cape Coast Metropolitan Assembly',
  'Central Gonja District',
  'Central Tongu District',
  'Chereponi District',
  'Daffiama Bussie Issa District',
  'Denkyembour District',
  'Dormaa Central Municipal',
  'Dormaa East District',
  'Dormaa West District',
  'East Gonja Municipal',
  'East Mamprusi Municipal',
  'Effutu Municipal',
  'Ejisu Municipal',
  'Ejura Sekyedumase Municipal',
  'Ekumfi District',
  'Ellembelle District',
  'Fanteakwa North District',
  'Fanteakwa South District',
  'Garu District',
  'Ga Central Municipal',
  'Ga East Municipal',
  'Ga North Municipal',
  'Ga South Municipal',
  'Ga West Municipal',
  'Gomoa Central District',
  'Gomoa East District',
  'Gomoa West District',
  'Guan District',
  'Gushiegu Municipal',
  'Ho Municipal',
  'Ho West District',
  'Hohoe Municipal',
  'Jaman North District',
  'Jaman South Municipal',
  'Jasikan Municipal',
  'Jirapa Municipal',
  'Jomoro Municipal',
  'Juaben Municipal',
  'Juaboso District',
  'Kade Municipal',
  'Kadjebi District',
  'Karaga District',
  'Kassena-Nankana Municipal',
  'Kassena-Nankana West District',
  'Keta Municipal',
  'Ketu North Municipal',
  'Ketu South Municipal',
  'Kintampo North Municipal',
  'Kintampo South District',
  'Komenda Edina Eguafo Abrem Municipal',
  'Kpandai District',
  'Kpone Katamanso Municipal',
  'Krachi East Municipal',
  'Krachi Nchumuru District',
  'Krachi West Municipal',
  'Krowor Municipal',
  'Kumbungu District',
  'Kumasi Metropolitan Assembly',
  'Kwabre East Municipal',
  'Kwaebibirem Municipal',
  'Kwahu Afram Plains North District',
  'Kwahu Afram Plains South District',
  'Kwahu East District',
  'Kwahu South District',
  'Kwahu West Municipal',
  'La Dade Kotopon Municipal',
  'La Nkwantanang Madina Municipal',
  'Lambussie District',
  'Lawra Municipal',
  'Ledzokuku Municipal',
  'Lower Manya Krobo Municipal',
  'Mamprugu Moagduri District',
  'Mampong Municipal',
  'Mfantsiman Municipal',
  'Mion District',
  'Mpohor District',
  'Nabdam District',
  'Nadowli Kaleo District',
  'Nandom Municipal',
  'Nanumba North Municipal',
  'Nanumba South District',
  'Nanton District',
  'New Juaben North Municipal',
  'New Juaben South Municipal',
  'Ningo Prampram District',
  'Nkoranza North District',
  'Nkoranza South Municipal',
  'North Dayi District',
  'North East Gonja District',
  'North Gonja District',
  'North Tongu District',
  'Nsawam-Adoagyiri Municipal',
  'Nkwanta North District',
  'Nkwanta South Municipal',
  'Nzema East Municipal',
  'Obuasi East District',
  'Obuasi Municipal',
  'Offinso Municipal',
  'Offinso North District',
  'Oforikrom Municipal',
  'Okaikwei North Municipal',
  'Okere District',
  'Old Tafo Municipal',
  'Prestea Huni Valley Municipal',
  'Pru East District',
  'Pru West District',
  'Pusiga District',
  'Saboba District',
  'Sagnarigu Municipal',
  'Savelugu Municipal',
  'Sawla-Tuna-Kalba District',
  'Sefwi Akontombra District',
  'Sekondi Takoradi Metropolitan Assembly',
  'Sekyere Afram Plains District',
  'Sekyere Central District',
  'Sekyere East District',
  'Sekyere Kumawu District',
  'Sekyere South District',
  'Sene East District',
  'Sene West District',
  'Shai Osudoku District',
  'Shama District',
  'Sissala East Municipal',
  'Sissala West District',
  'South Dayi District',
  'South Tongu District',
  'Suaman District',
  'Suame Municipal',
  'Suhum Municipal',
  'Sunyani Municipal',
  'Sunyani West District',
  'Tamale Metropolitan Assembly',
  'Tano North Municipal',
  'Tano South Municipal',
  'Tarkwa Nsuaem Municipal',
  'Tatale Sanguli District',
  'Techiman Municipal',
  'Techiman North District',
  'Tema Metropolitan Assembly',
  'Tema West Municipal',
  'Tempane District',
  'Tolon District',
  'Twifo Atti Morkwa District',
  'Twifo Hemang Lower Denkyira District',
  'Upper Denkyira East Municipal',
  'Upper Denkyira West District',
  'Upper Manya Krobo District',
  'Upper West Akim District',
  'Wa East District',
  'Wa Municipal',
  'Wa West District',
  'Wassa East District',
  'Weija Gbawe Municipal',
  'Wenchi Municipal',
  'West Akim Municipal',
  'West Gonja Municipal',
  'West Mamprusi Municipal',
  'Wiawso Municipal',
  'Yendi Municipal',
  'Yilo Krobo Municipal',
  'Yunyoo-Nasuan District',
  'Zabzugu District'
];
